name: get-gfs
channels:
  - defaults
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - pip
  - requests
  - xarray
  #- cartopy
  - typer
  - netCDF4
  - plotly=4.14.3
  - basemap
  - matplotlib=3.2
  - pip:
    - pydap==3.2.2
    - black

